services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tourze\CouponSendPlanBundle\DataFixtures\:
        resource: '../../DataFixtures/*'
        tags: ['doctrine.fixture.orm']